name: fibscli_lib
description: low-level Dart client library for FIBS

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  socket_io_client: ^0.9.12
  logging: ^0.11.4
  quiver: ^2.1.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.7

