name: fibscli_lib
description: low-level Dart client library for FIBS
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  quiver: ^3.2.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  all_lint_rules_community: ^0.0.38
  test: ^1.15.7
